### ISSUE TITLE
bower info

### ISSUE THREAD

**Issue by Nimble-Momonga** [humangeo/leaflet-tilefilter#2]
bower.json and package.json has a reference to "dist/TileLayer.Filter.min.js" and should be "dist/leaflet-tilefilter.min.js"

**Comment by sfairgrieve** [comment]
Thanks for pointing this out.  I updated the file naming when I ported the build to grunt and completely forgot about the bower/package references.

**Comment by sfairgrieve** [comment]
This should now be fixed.
