### ISSUE TITLE
Use with Webpack?

### ISSUE THREAD

**Issue by fnick851** [humangeo/leaflet-tilefilter#8]
Probably a dumb question, but what is the most appropriate way to integrate this with a Webpack project?

I am working on a project built with Vue, Leaflet, and Webpack. Could you provide some guidance on this? Thanks.

**Comment by sfairgrieve** [comment]
I haven't used this with webpack before, but I think it should be possible.  The current codebase doesn't use modules or support newer ways of exporting functions, but I think you could add the specific JS file `leaflet-tilefilter.js` to the entry list in your webpack config and use the webpack `ProvidePlugin` to make Leaflet's global L property available:  https://webpack.js.org/guides/shimming/.
